# /* ---- 💫 https://github.com/vmnavarro94/HyprBrigade 💫 ---- */
# /* Tokyo Night theme */

$background = rgb(1a1b26)
$foreground = rgb(a9b1d6)
$color0 = rgb(414868)
$color1 = rgb(f7768e)
$color2 = rgb(73daca)
$color3 = rgb(e0af68)
$color4 = rgb(7aa2f7)
$color5 = rgb(bb9af7)
$color6 = rgb(7dcfff)
$color7 = rgb(c0caf5)
$color8 = rgb(414868)
$color9 = rgb(f7768e)
$color10 = rgb(73daca)
$color11 = rgb(e0af68)
$color12 = rgb(7aa2f7)
$color13 = rgb(bb9af7)
$color14 = rgb(7dcfff)
$color15 = rgb(c0caf5)
