# /* ---- 💫 https://github.com/vmnavarro94/HyprBrigade 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

# Spotify always opens in workspace 2
windowrule = match:class ^(Spotify|spotify)$, workspace 2

# Discord always opens in workspace 6
windowrule = match:class ^(Discord|discord)$, workspace 6

# Slack always opens in workspace 8
windowrule = match:class ^(Slack|slack)$, workspace 8
