# /* ---- 💫 https://github.com/vmnavarro94/HyprBrigade 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(272A2A)
$foreground = rgb(CBDCDE)
$color0 = rgb(4C4F4F)
$color1 = rgb(1D2524)
$color2 = rgb(1A2627)
$color3 = rgb(4C4435)
$color4 = rgb(375053)
$color5 = rgb(765F44)
$color6 = rgb(4F747A)
$color7 = rgb(ACC5C8)
$color8 = rgb(788A8C)
$color9 = rgb(263130)
$color10 = rgb(233334)
$color11 = rgb(665B47)
$color12 = rgb(496A6F)
$color13 = rgb(9E7F5B)
$color14 = rgb(6A9BA2)
$color15 = rgb(ACC5C8)
