# /* ---- 💫 https://github.com/vmnavarro94/HyprBrigade 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CBDCDE
background         #272A2A
cursor             #778789

active_tab_foreground     #272A2A
active_tab_background     #CBDCDE
inactive_tab_foreground   #CBDCDE
inactive_tab_background   #272A2A

active_border_color   #CBDCDE
inactive_border_color #272A2A
bell_border_color     #1D2524

color0      #4C4F4F
color1		#1D2524
color2		#1A2627
color3		#4C4435
color4		#375053
color5		#765F44
color6		#4F747A
color7		#ACC5C8
color8		#788A8C
color9		#263130
color10		#233334
color11		#665B47
color12		#496A6F
color13		#9E7F5B
color14		#6A9BA2
color15		#ACC5C8
